model:
  # name: "llava-hf/llava-1.5-7b-hf"
  name: "qwen-vl-chat-7b"
  max_tokens: 512
  temperature: 0.7

memory:
  short_term_ttl: 3600  # 1 hour
  long_term_db: "chromadb"
  embedding_model: "all-MiniLM-L6-v2"

camera:
  device: 0  # Use built-in webcam
  capture_interval: 30  # seconds

training:
  interval_hours: 24
  epochs_per_training: 3
  lora_rank: 16
  learning_rate: 5e-5

tools:
  enabled:
    - web_search
    - observe_surroundings
    - memory_query
